apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
spec:
  containers:
    - name: consumer-container-1
      image: sebastianalexandru/consumer:latest
      ports:
        - containerPort: 8081
      env:
        - name: BOOTSTRAP_HOST
          value: kafka-1-ip-service
        - name: BOOTSTRAP_PORT
          value: "9092"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgis-ip-service:5432/spring_kafka_db

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-1-ip-service
spec:
  type: ClusterIP
  selector:
    component: consumer-1
  ports:
    - port: 8081
      targetPort: 8081
