version: '3'
services:

  postgis:
    image: postgis/postgis:latest
    ports:
      - "5433:5432"
    container_name: postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_kafka_db


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: GeoJson8
    depends_on:
      - zookeeper

  consumer:
    image: sebastianalexandru/consumer:latest
    ports:
      - "8081:8081"
    environment:
      BOOTSTRAP_HOST: kafka
      BOOTSTRAP_PORT: 9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/spring_kafka_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


  producer:
    image: sebastianalexandru/producer:latest
    ports:
      - "8082:8082"
    environment:
      KAFKA_TOPIC: GeoJson8
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092

#  kafka-web-gui:
#    image: tchiotludo/akhq
#    ports:
#      - "8091:8080"
#    environment:
#      AKHQ_CONFIGURATION: |
#        akhq:
#          connections:
#            docker-kafka-server:
#              properties:
#                bootstrap.servers: "kafka:9092"
#                request.timeout.ms: 60000