apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
spec:
  containers:
    - name: producer-container-1
      image: sebastianalexandru/producer:latest
      ports:
        - containerPort: 8082
      env:
        - name: KAFKA_TOPIC
          value: "GeoJson8"
        - name: KAFKA_HOST
          value: kafka-1-ip-service
        - name: KAFKA_PORT
          value: "9092"

---
apiVersion: v1
kind: Service
metadata:
  name: producer-1-ip-service
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - name: producer
      port: 8082